const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const vm = require('vm');

class FakeRange { constructor(sheet,row,col,rows=1,cols=1){Object.assign(this,{sheet,row,col,rows,cols});} getValue(){return this.sheet.get(this.row,this.col);} setValue(value){this.sheet.write(this.row,this.col,value);return this;} getValues(){return Array.from({length:this.rows},(_,r)=>Array.from({length:this.cols},(_,c)=>this.sheet.get(this.row+r,this.col+c)));} setValues(values){values.forEach((line,r)=>line.forEach((value,c)=>this.sheet.write(this.row+r,this.col+c,value)));return this;} }
class FakeSheet { constructor(){this.cells=new Map();this.failAt=null;this.maxRows=1;this.maxColumns=2;} key(row,col){return `${row}:${col}`;} get(row,col){return this.cells.get(this.key(row,col))||'';} write(row,col,value){const text=String(value);if(text.length>50000)throw new Error('cell character limit exceeded');if(this.failAt===this.key(row,col))throw new Error('injected write failure');if(/^[=+\-@]/.test(text)){this.cells.set(this.key(row,col),'#FORMULA_RESULT');return;}this.cells.set(this.key(row,col),value);} getRange(a,b,c,d){if(typeof a==='string'){const match=/^([A-Z])(\d+)$/.exec(a);if(!match)throw new Error(`unsupported ${a}`);return new FakeRange(this,Number(match[2]),match[1].charCodeAt(0)-64);}if(a+(c||1)-1>this.maxRows||b+(d||1)-1>this.maxColumns)throw new Error('range exceeds sheet capacity');return new FakeRange(this,a,b,c,d);} getMaxRows(){return this.maxRows;}getMaxColumns(){return this.maxColumns;}insertRowsAfter(_after,count){this.maxRows+=count;}insertColumnsAfter(_after,count){this.maxColumns+=count;} }
const source=fs.readFileSync('Code.gs','utf8');
const context={Logger:{log(){}},Utilities:{DigestAlgorithm:{SHA_256:'SHA_256'},Charset:{UTF_8:'UTF_8'},computeDigest(_algorithm,text){return Array.from(crypto.createHash('sha256').update(text,'utf8').digest(),value=>value>127?value-256:value);}}};
vm.createContext(context);vm.runInContext(source,context);
assert.strictEqual(typeof context.readAppData_,'function');assert.strictEqual(typeof context.writeAppData_,'function');
const legacySheet=new FakeSheet();const legacyJson=JSON.stringify({stocks:[{ticker:'GOOGL'}],updatedAt:'legacy'});legacySheet.getRange('A1').setValue(legacyJson);legacySheet.getRange('B1').setValue('legacy-time');assert.strictEqual(context.readAppData_(legacySheet),legacyJson);assert.strictEqual(context.readAppDataSavedAt_(legacySheet),'legacy-time');
const sheet=new FakeSheet();const firstState={updatedAt:'2026-09-15T01:00:00.000Z',journal:[{content:'가'.repeat(120000)}],txns:[{source:'agent',sourceId:'trade:first'}]};context.writeAppData_(sheet,firstState,firstState.updatedAt);assert.deepStrictEqual(JSON.parse(context.readAppData_(sheet)),firstState);assert.ok(String(sheet.getRange('A1').getValue()).length<50000);for(const value of sheet.cells.values())assert.ok(String(value).length<=50000);assert.strictEqual(context.readAppDataSavedAt_(sheet),firstState.updatedAt);
const manifestBefore=JSON.parse(sheet.getRange('A1').getValue());const inactiveColumn=manifestBefore.active==='C'?4:3;const secondState={...firstState,updatedAt:'2026-09-15T02:00:00.000Z',journal:[{content:'나'.repeat(120000)}]};sheet.failAt=sheet.key(2,inactiveColumn);assert.throws(()=>context.writeAppData_(sheet,secondState,secondState.updatedAt),/injected write failure/);sheet.failAt=null;assert.deepStrictEqual(JSON.parse(context.readAppData_(sheet)),firstState);
const emojiState={updatedAt:'2026-09-15T03:00:00.000Z',note:'🚀'.repeat(45000)};context.writeAppData_(sheet,emojiState,emojiState.updatedAt);assert.deepStrictEqual(JSON.parse(context.readAppData_(sheet)),emojiState);
for(const marker of ['=','+','-','@']){const json='{"x":"'+'a'.repeat(39994)+marker+'SUM(1,1)"}';context.writeAppData_(sheet,json,'2026-09-15T04:00:00.000Z');assert.strictEqual(context.readAppData_(sheet),json);}
console.log('chunked app-data storage: PASS');
